name: Send Email Weekly

on:
  schedule:
    - cron: '0 18 * * 2'  # Ejecutar todos los martes a las 6 PM EST
    workflow_dispatch:  # Permite ejecutar manualmente el flujo de trabajo

jobs:
  sendEmail:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r EmailAutomation/requirements.txt  # Instalar dependencias

      - name: Run Email Script
        run: python EmailAutomation/send_email.py
        env:
          SHAREPOINT_USERNAME: ${{ secrets.SHAREPOINT_USERNAME }}  # Almacena tus credenciales en Secrets
          SHAREPOINT_PASSWORD: ${{ secrets.SHAREPOINT_PASSWORD }}  # Almacena tus credenciales en Secrets
